USE [Coupons]
GO

/* ==============================================
   Creates Coupons project DB
   ============================================== */


SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO




/* ==============================================
   USERS table
   ============================================== */
if OBJECT_ID ('USERS') is not null
	DROP TABLE dbo.USERS
GO

CREATE TABLE dbo.USERS
(
	USER_ID  			int					IDENTITY(1,1)NOT NULL,

	SYS_CREATION_DATE	datetime			not null,
	SYS_UPDATE_DATE		datetime			not null,
	CREATED_BY_USER_ID	int					not null,
	UPDATED_BY_USER_ID	int					not null,

	USER_PROFILE_ID  	int 				NOT NULL, /* 1 = Admin , 2 = Company, 3 = Customer */
	USER_NAME			varchar(max)		NOT NULL,
	LOGIN_NAME			varchar(100)		NOT NULL,
	LOGIN_PASSWORD		varchar(max)		NOT NULL,


	CONSTRAINT [PK_USERS] PRIMARY KEY CLUSTERED 
	(
		USER_ID ASC
	)
) ON [PRIMARY]
GO

ALTER TABLE USERS ADD CONSTRAINT DF_USERS_SYS_CREATION_DATE DEFAULT GETDATE() FOR SYS_CREATION_DATE;
GO

ALTER TABLE USERS ADD CONSTRAINT DF_USERS_SYS_UPDATE_DATE DEFAULT GETDATE() FOR SYS_UPDATE_DATE;
GO


CREATE UNIQUE INDEX IDX_USERS_LOGIN_NAME ON USERS (LOGIN_NAME);  
GO



insert into USERS ( USER_PROFILE_ID, CREATED_BY_USER_ID, UPDATED_BY_USER_ID, USER_NAME, LOGIN_NAME, LOGIN_PASSWORD ) select '1', 1, 1 , 'USER 1', 'admin', '1234';

insert into USERS ( USER_PROFILE_ID, CREATED_BY_USER_ID, UPDATED_BY_USER_ID, USER_NAME, LOGIN_NAME, LOGIN_PASSWORD ) select '2', 1, 1 , 'USER 2', 'comp1' , '1234';
insert into USERS ( USER_PROFILE_ID, CREATED_BY_USER_ID, UPDATED_BY_USER_ID, USER_NAME, LOGIN_NAME, LOGIN_PASSWORD ) select '2', 1, 1 , 'USER 3', 'comp2' , '1234';

insert into USERS ( USER_PROFILE_ID, CREATED_BY_USER_ID, UPDATED_BY_USER_ID, USER_NAME, LOGIN_NAME, LOGIN_PASSWORD ) select '3', 1, 1 , 'USER 4', 'cust1' , '1234';
insert into USERS ( USER_PROFILE_ID, CREATED_BY_USER_ID, UPDATED_BY_USER_ID, USER_NAME, LOGIN_NAME, LOGIN_PASSWORD ) select '3', 1, 1 , 'USER 5', 'cust2' , '1234';


/* ==============================================
   COMPANYS table
   ============================================== */
if OBJECT_ID ('CUSTOMER_COUPON') is not null
	DROP TABLE dbo.CUSTOMER_COUPON
GO

if OBJECT_ID ('COUPONS') is not null
	DROP TABLE dbo.COUPONS
GO


if OBJECT_ID ('COMPANYS') is not null
	DROP TABLE dbo.COMPANYS
GO


CREATE TABLE dbo.COMPANYS
(
	COMPANY_ID			bigint IDENTITY(1,1)NOT NULL,

	SYS_CREATION_DATE	datetime			not null,
	SYS_UPDATE_DATE		datetime			not null,
	CREATED_BY_USER_ID	int					not null,
	UPDATED_BY_USER_ID	int					not null,

	USER_ID				int					NOT NULL,
	COMPANY_NAME		varchar(900)		NOT NULL,
	COMPANY_EMAIL		varchar(max)		NOT NULL,


	CONSTRAINT [PK_COMPANYS] PRIMARY KEY CLUSTERED 
	(
		COMPANY_ID ASC
	)
) ON [PRIMARY]
GO

ALTER TABLE COMPANYS ADD CONSTRAINT DF_COMPANYS_SYS_CREATION_DATE DEFAULT GETDATE() FOR SYS_CREATION_DATE;
GO

ALTER TABLE COMPANYS ADD CONSTRAINT DF_COMPANYS_SYS_UPDATE_DATE DEFAULT GETDATE() FOR SYS_UPDATE_DATE;
GO

CREATE UNIQUE INDEX IDX_COMPANYS_COMPANY_NAME	ON COMPANYS (COMPANY_NAME);  
GO

CREATE UNIQUE INDEX IDX_COMPANYS_USER_ID		ON COMPANYS (USER_ID);  
GO


insert into COMPANYS ( USER_ID, CREATED_BY_USER_ID, UPDATED_BY_USER_ID, COMPANY_NAME, COMPANY_EMAIL ) select 2, 1, 1, 'Company 1' , 'comp1@gmail.com';
insert into COMPANYS ( USER_ID, CREATED_BY_USER_ID, UPDATED_BY_USER_ID, COMPANY_NAME, COMPANY_EMAIL ) select 3, 1, 1, 'Company 2' , 'comp2@gmail.com';



/* ==============================================
   CUSTOMERS table
   ============================================== */
if OBJECT_ID ('CUSTOMERS') is not null
	DROP TABLE dbo.CUSTOMERS
GO

CREATE TABLE dbo.CUSTOMERS
(
	CUSTOMER_ID			bigint IDENTITY(1,1)NOT NULL,

	SYS_CREATION_DATE	datetime			not null,
	SYS_UPDATE_DATE		datetime			not null,
	CREATED_BY_USER_ID	int					not null,
	UPDATED_BY_USER_ID	int					not null,

	USER_ID				int					NOT NULL,
	CUSTOMER_NAME		varchar(900)		NOT NULL,

	CONSTRAINT [PK_CUSTOMERS] PRIMARY KEY CLUSTERED 
	(
		CUSTOMER_ID ASC
	)
) ON [PRIMARY]
GO

ALTER TABLE CUSTOMERS ADD CONSTRAINT DF_CUSTOMERS_CREATION_DATE DEFAULT GETDATE() FOR SYS_CREATION_DATE;
GO

ALTER TABLE CUSTOMERS ADD CONSTRAINT DF_CUSTOMERS_UPDATE_DATE DEFAULT GETDATE() FOR SYS_UPDATE_DATE;
GO

CREATE UNIQUE INDEX IDX_CUSTOMERSS_CUSTOMER_NAME ON CUSTOMERS (CUSTOMER_NAME);  
GO

CREATE UNIQUE INDEX IDX_CUSTOMERS_USER_ID		 ON CUSTOMERS (USER_ID);  
GO

insert into CUSTOMERS ( USER_ID, CREATED_BY_USER_ID, UPDATED_BY_USER_ID, CUSTOMER_NAME  ) select 4, 1, 1, 'CUSTOMER 1'  ;
insert into CUSTOMERS ( USER_ID, CREATED_BY_USER_ID, UPDATED_BY_USER_ID, CUSTOMER_NAME  ) select 5, 1, 1, 'CUSTOMER 2'  ;
go


/* ==============================================
   COUPONS table
   ============================================== */
if OBJECT_ID ('COUPONS') is not null
	DROP TABLE dbo.COUPONS
GO

CREATE TABLE dbo.COUPONS
(
	COUPON_ID			bigint IDENTITY(1,1)	NOT NULL,

	SYS_CREATION_DATE	datetime			not null,
	SYS_UPDATE_DATE		datetime			not null,
	CREATED_BY_USER_ID	int					not null,
	UPDATED_BY_USER_ID	int					not null,

	COMPANY_ID			bigint				NOT NULL,
	COUPON_TITLE		varchar(900)		NOT NULL,
	COUPON_START_DATE	datetime			NOT NULL,
	COUPON_END_DATE		datetime			NOT NULL,
	COUPONS_IN_STOCK	int				    NOT NULL,
	COUPON_TYPE_ID		int					NOT NULL,
	COUPON_MESSAGE		varchar(max)		,
	COUPON_PRICE		float			    NOT NULL,
	IMAGE_FILE_NAME		varchar(max)		,


	CONSTRAINT [PK_COUPONS] PRIMARY KEY CLUSTERED 
	(
		COUPON_ID ASC
	)
) ON [PRIMARY]
GO

ALTER TABLE COUPONS ADD CONSTRAINT DF_COUPONS_SYS_CREATION_DATE DEFAULT GETDATE() FOR SYS_CREATION_DATE;
GO

ALTER TABLE COUPONS ADD CONSTRAINT DF_COUPONS_SYS_UPDATE_DATE DEFAULT GETDATE() FOR SYS_UPDATE_DATE;
GO

CREATE UNIQUE INDEX IDX_COUPONS_COUPON_TITLE		ON COUPONS (COUPON_TITLE);  
GO

ALTER TABLE COUPONS ADD CONSTRAINT FK_COUPONS_COMPANY_ID FOREIGN KEY (COMPANY_ID) REFERENCES COMPANYS (COMPANY_ID) ON DELETE CASCADE;
GO

/* ==============================================
   CUSTOMER_COUPON table
   ============================================== */
if OBJECT_ID ('CUSTOMER_COUPON') is not null
	DROP TABLE dbo.CUSTOMER_COUPON
GO

CREATE TABLE dbo.CUSTOMER_COUPON
(

	INTERNAL_ID			bigint IDENTITY(1,1)	NOT NULL,	

	CUSTOMER_ID			bigint				NOT NULL,
	COUPON_ID			bigint				NOT NULL,

	SYS_CREATION_DATE	datetime			not null,
	SYS_UPDATE_DATE		datetime			not null,
	CREATED_BY_USER_ID	int					not null,
	UPDATED_BY_USER_ID	int					not null,
	


	CONSTRAINT [PK_CUSTOMER_COUPON] PRIMARY KEY CLUSTERED 
	(
		 CUSTOMER_ID	ASC
		,COUPON_ID		ASC 
	)
) ON [PRIMARY]
GO

ALTER TABLE CUSTOMER_COUPON ADD CONSTRAINT DF_CUSTOMER_COUPON_CREATION_DATE DEFAULT GETDATE() FOR SYS_CREATION_DATE;
GO

ALTER TABLE CUSTOMER_COUPON ADD CONSTRAINT DF_CUSTOMER_COUPON_UPDATE_DATE DEFAULT GETDATE() FOR SYS_UPDATE_DATE;
GO

CREATE UNIQUE INDEX IDX_CUSTOMER_COUPON_INTERNAL_ID		ON CUSTOMER_COUPON (INTERNAL_ID);  
GO


ALTER TABLE CUSTOMER_COUPON ADD CONSTRAINT FK_CUSTOMER_COUPON_COUPON_ID FOREIGN KEY (COUPON_ID) REFERENCES COUPONS (COUPON_ID) ON DELETE CASCADE;
GO

ALTER TABLE CUSTOMER_COUPON ADD CONSTRAINT FK_CUSTOMER_COUPON_CUSTOMER_ID FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS (CUSTOMER_ID) ON DELETE CASCADE;
GO


/* ==============================================
   End of script
   ============================================== */
SET ANSI_PADDING OFF
GO


